# Generated by Django 6.0.5 on 2026-05-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_service_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='post',
            name='background_title',
            field=models.CharField(blank=True, default='SUJAL', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='layered_character_img',
            field=models.ImageField(blank=True, null=True, upload_to='posts_cutouts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_text',
            field=models.CharField(default='Liked by 210 others', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='main_post_img',
            field=models.ImageField(blank=True, null=True, upload_to='posts_framed/'),
        ),
    ]
