# Generated by Django 6.0.5 on 2026-05-06 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_image_remove_post_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='background_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='layered_character_img',
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_text',
            field=models.CharField(blank=True, default='Liked by 210 others', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_post_img',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
